blogsite/urls.py
from django.contrib import admin
from django.urls import include, path # modificar esta linha


urlpatterns = [
    path('', include('staticpages.urls')),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
  path('', views.PostListView.as_view(), name='index'),
  path('search/', views.search_posts, name='search'),
  path('create/', views.PostCreateView.as_view(), name='create'),
  path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
  path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
  path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'), # adicione esta linha
    path('', views.index, name='index'),
]

posts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=2047)
    image_url = models.URLField(max_length=200, null=True)
    def get_absolute_url(self):
            return reverse('posts:detail', kwargs={'pk': self.pk})
    def __str__(self):
        return f'{self.title} ({self.date})'

staticpages/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms

class MovieForm(forms.Form):
    title = forms.CharField(label='Título', max_length=100)
    content = forms.CharField(label='Título', max_length=2047)
    date = forms.DateTimeField(auto_now_add=True)
    image_url = forms.URLField(label='URL da imagem', max_length=100)

posts/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
# Create your views here.
from django.http import HttpResponse
from .temp_data import post_data
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Post
from django.views import generic

class PostListView(generic.ListView):
    model = Post
    template_name = 'posts/index.html'

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'posts/detail.html'

class PostCreateView(generic.CreateView):
    model = Post
    template_name = 'posts/create.html'
    fields = ['title', 'content', 'image_url']

class PostUpdateView(generic.UpdateView):
    model = Post
    template_name = 'posts/update.html'
    fields = ['title', 'content', 'image_url']

class PostDeleteView(generic.DeleteView):
    model = Post
    template_name = 'posts/delete.html'
    success_url = reverse_lazy('posts:index')

def search_posts(request):
  context = {}
  if request.GET.get('query', False):
    search_term = request.GET['query'].lower()
    post_list = Post.objects.filter(name__icontains=search_term)
    context = {"post_list": post_list}
  return render(request, 'posts/search.html', context)

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Post</h2>
<form method="POST" action="{% url 'posts:create' %}">
    {% csrf_token %}
    <h4>
        <label for="id_title">Título:</label>
        <input type="text" name="title" id="id_title" />
    </h4>
    <p>
        <label for="id_content">Conteúdo:</label>
        <input type="text" name="content" id="id_content" />
    </p>
    <p>
        <label for="id_image_url">URL da Imagem:</label>
        <input type="url" name="image_url" id="id_image_url" />
    </p>
    <button type="submit">Criar</button>
</form>

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o post "{{ post.title }}"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }}
{% endblock title %}

{% block content %}
<h2>Detalhes do Post {{ post.title }}</h2>

<section class="dados-de-filme">
    <img src="{{ post.image_url }}" alt="Imagem do post {{ post.title}}">
    <ul>
        <li><h3> {{ post.title }} </h3></li>
        <li><h6> {{ post.date}} </h6></li>
        <li> {{ post.content }}</li>
        <li><a href="{% url 'posts:update' post.id %}">Editar</a></li>
        <li><a href="{% url 'posts:delete' post.id %}">Apagar</a></li>
    </ul>
</section>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Posts</h2>
{% if post_list %}
<section>
  <p>Muitos resultados? <a href="{% url 'posts:search' %}">Buscar Posts</a></p>
  <p>Não encontrou o post? <a href="{% url 'posts:create' %}">Adicionar Novo Post</a></p>
</section>
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <a href="{% url 'posts:detail' post.id %}"><img src="{{ post.image_url }}"
                alt="Imagem do post {{ post.title}}"></a>
        <p>{{ post.title }}</p>
        <h6>{{ post.date}} </h6>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Posts por Título</h2>
<form action="{% url 'posts:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <img src="{{ post.image_url }}" alt="Imagem do Post {{ post.title}}">
        <p>{{ post.title }}</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post para a busca.</p>
{% endif %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Post {{ post.title }}</h2>
<form method="POST" action="{% url 'posts:update' post.id%}">
    {% csrf_token %}
    <p>
        <label for="id_title">Título:</label>
        <input type="text" name="title" id="id_title" value="{{ post.title }}" />
    </p>
    <p>
        <label for=" id_content">Conteúdo:</label>
        <input type="text" name="content" id="id_content" value="{{ post.content }}" />
    </p>
    <p>
        <label for=" id_image_url">URL da imagem:</label>
        <input type="url" name="image_url" id="id_image_url" value="{{post.image_url}}" />
    </p>
    <button type="submit">Atualizar</button>
</form>
{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Meu blog pessoal</i></h1>
<p>A Página para meus posts</p>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Meu blog
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}">
            <p>Blog</p>
        </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'posts:index' %}">Posts</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2022</small>
        </p>
    </footer>
</body>

</html>